version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    
hooks:
  AfterInstall:
    - location: install_services.sh
      timeout: 300
      runas: root
    - location: start_server.sh
      timeout: 600
      runas: root
    - location: run_dast.sh
      timeout: 300
      runas: root
